bboard/urls.py
from django.urls import path

from .views import BbIndexView, ByRubricListView, BbCreateView, BbDetailView, leave_comment, \
    BbEditView, BbDeleteView, ClientRoom, RegisterUserView, BboardLoginView, BboardLogoutView, \
    RubricCreateView, RubricDeleteView, rubrics, process_search_results, ImgCreateView

app_name = 'bboard'

urlpatterns = [
    path('rubric/<int:rubric_id>/', ByRubricListView.as_view(), name='by_rubric'),
    path('', BbIndexView.as_view(), name='index'),
    path('add/', BbCreateView.as_view(), name='add'),
    path('add/rubric', RubricCreateView.as_view(), name='add_rubric'),
    path('add/rubric/formset/', rubrics, name='add_rubric_formset'),
    path('add/file/', ImgCreateView.as_view(), name='add_file'),
    path('edit/<int:bb_id>/', BbEditView.as_view(), name='edit'),
    path('delete/<int:bb_id>/', BbDeleteView.as_view(), name='delete'),
    path('delete/rubric/<int:rubric_id>/', RubricDeleteView.as_view(), name='delete_rubric'),
    path('detail/<int:bb_id>/', BbDetailView.as_view(), name='detail_bb'),
    path('detail/<int:bb_id>/leave_comment', leave_comment, name='leave_comment'),
    path('client_room/', ClientRoom.as_view(), name='client_room'),
    path('authentication/', RegisterUserView.as_view(), name='register_page'),
    path('login/', BboardLoginView.as_view(), name='login'),
    path('logout/', BboardLogoutView.as_view(), name='logout'),
    path('search/bb/', process_search_results, name='search'),
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bboard.urls', namespace = 'bboard')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bboard/models.py
from django.conf import settings
from django.core import validators
from django.core.exceptions import ValidationError
from django.db import models


def validate_min_value(val):
    if val < 0:
        raise ValidationError('Число %(value)s меньше 0, исправьте это', params={'value': val})


def validate_proper_string_name(s, banned_chars=(' ', ',', '.', ':', ';'), numbers=(1, 2, 3, 4, 5, 6, 7, 8, 9, 0)):
    for i in s:
        if i in numbers or i in banned_chars:
            raise ValidationError('В данном поле должны быть только буквы, эти символы также недопустимы: %s' % ', '
                                  .join(banned_chars))


class RubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().order_by('name')

    def order_by_bb_count(self):
        return super().get_queryset.annotate(cnt=models.Count('bb')).order_by('-cnt')


class Bb(models.Model):
    KINDS = (
        ('Покупка', 'Покупка'),
        ('Продажа', 'Продажа'),
        ('Обмен', 'Обмен'),
        (None, 'Продажа/Обмен'),
    )
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL,
                                verbose_name='Создатель объявления')
    kind = models.CharField(max_length=8, choices=KINDS, default='Продажа', verbose_name='Цель объявления')
    title = models.CharField(max_length=20, verbose_name='Товар')
    content = models.TextField(null=True, blank=True, verbose_name='Описание')
    price = models.FloatField(null=True, blank=True, verbose_name="Цена", validators=[validate_min_value])
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')
    rubric = models.ForeignKey('Rubric', null=True, on_delete=models.CASCADE, verbose_name='Рубрика')
    image = models.ImageField(null=True, upload_to='archive',
                              validators=[validators.FileExtensionValidator(allowed_extensions=('gif', 'png', 'jpg'))],
                              error_messages={'invalid_extension': 'Выбранный тип файла не поддерживается'},
                              verbose_name='Фото товара')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Объявления'
        verbose_name = 'Объявление'
        ordering = ['-published']


class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, verbose_name='Название', unique=True,
                            validators=[validate_proper_string_name])

    objects = RubricManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Рубрики'
        verbose_name = 'Рубрика'
        ordering = ['name']


class Comment(models.Model):
    bb = models.ForeignKey(Bb, on_delete=models.CASCADE)
    author_name = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL,
                                    verbose_name='Имя комментатора')
    comm_text = models.TextField(verbose_name='Комментарий')
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'
        ordering = ['-published']


class Img(models.Model):
    img = models.ImageField(verbose_name='Изображение', upload_to='archive',
                            validators=[validators.FileExtensionValidator(allowed_extensions=('gif', 'png', 'jpg'))],
                            error_messages={'invalid_extension': 'Выбранный тип файла не поддерживается'})
    desc = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

    def __str__(self):
        return self.desc

bboard/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.forms.widgets import Textarea

from .models import Bb, Rubric, Img


class ImgForm(ModelForm):
    class Meta:
        model = Img
        fields = ('desc', 'img')


class SearchRubric(forms.Form):
    keyword = forms.CharField(max_length=20, label='Искомое слово')
    rubric = forms.ModelChoiceField(queryset=Rubric.objects.all(), label='Рубрика')


class RubricForm(ModelForm):
    class Meta:
        model = Rubric
        fields = ('name',)
        widgets = {'desc': Textarea()}


class BbForm(ModelForm):
    class Meta:
        model = Bb
        fields = ('title', 'content', 'image', 'rubric', 'kind', 'price')
        labels = {'title': 'Название товара'}
        help_text = {'rubric': 'Не забудьте указать рубрику!'}


class AuthUserForm(AuthenticationForm, ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class RegisterUserForm(ModelForm):
    captcha = CaptchaField(label='Решите пример: ', label_suffix='',
                             error_messages={'invalid': 'Неправильно решен пример'})

    class Meta:
        model = User
        fields = ('username', 'password', 'email')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

bboard/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.db import transaction
from django.db.models import Q
from django.forms import modelformset_factory
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from .forms import BbForm, AuthUserForm, RegisterUserForm, RubricForm, SearchRubric, ImgForm
from .models import Bb, Rubric, Comment


class BbIndexView(TemplateView):
    template_name = 'bboard/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        context['bbs'] = Bb.objects.all()
        return context


class ClientRoom(LoginRequiredMixin, TemplateView):
    template_name = 'bboard/client_room.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class BboardLoginView(LoginView):
    template_name = 'bboard/login.html'
    initial = {'username': '', 'password': ''}
    form_class = AuthUserForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_success_url(self):
        return reverse_lazy('bboard:client_room')


class BboardLogoutView(LogoutView):
    next_page = 'bboard:index'


class RegisterUserView(CreateView):
    model = User
    template_name = 'bboard/register_page.html'
    form_class = RegisterUserForm

    def form_valid(self, form):
        form_valid = super().form_valid(form)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        auth_user = authenticate(username=username, password=password)
        login(self.request, auth_user)
        transaction.commit()
        return form_valid

    def get_success_url(self):
        return reverse('bboard:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class BbDetailView(DetailView):
    model = Bb
    template_name = 'bboard/detail_bb.html'
    pk_url_kwarg = 'bb_id'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        current_bb = Bb.objects.get(pk=self.kwargs['bb_id'])
        context['rubrics'] = Rubric.objects.all()
        context['comments'] = Comment.objects.all()
        context['current_bb'] = current_bb
        context['latest_comments_list'] = current_bb.comment_set.order_by('-id')[:10]
        return context


class ByRubricListView(ListView):
    template_name = 'bboard/by_rubric.html'
    pk_url_kwarg = 'rubric_id'
    context_object_name = 'bbs'

    def get_queryset(self):
        return Bb.objects.filter(rubric=self.kwargs['rubric_id'])

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['rubrics'] = Rubric.objects.all()
        context['current_rubric'] = Rubric.objects.get(pk=self.kwargs['rubric_id'])
        return context


class BbCreateView(LoginRequiredMixin, CreateView):
    template_name = 'bboard/create.html'
    form_class = BbForm
    initial = {'price': 0.0}

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.creator = self.request.user
        obj.save()
        transaction.commit()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('bboard:detail_bb', kwargs={'bb_id': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context


class RubricCreateView(LoginRequiredMixin, CreateView):
    template_name = 'bboard/create_a_rubric.html'
    form_class = RubricForm

    def form_valid(self, form):
        form.save()
        transaction.commit()
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('bboard:by_rubric', kwargs={'rubric_id': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class BbEditView(LoginRequiredMixin, UpdateView):
    template_name = 'bboard/edit.html'
    form_class = BbForm
    model = Bb
    pk_url_kwarg = 'bb_id'

    def form_valid(self, form):
        form.save()
        transaction.commit()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('bboard:detail_bb', kwargs={'bb_id': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context


class BbDeleteView(LoginRequiredMixin, DeleteView):
    model = Bb
    template_name = 'bboard/delete.html'
    pk_url_kwarg = 'bb_id'

    def get_success_url(self):
        return reverse('bboard:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context


class RubricDeleteView(LoginRequiredMixin, DeleteView):
    model = Rubric
    template_name = 'bboard/delete_rubric.html'
    pk_url_kwarg = 'rubric_id'

    def get_success_url(self):
        return reverse('bboard:index')

    def get_context_data(self, **kwargs):
        q = Q(rubric__name=self.object.name)
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        context['bbs'] = Bb.objects.filter(q)
        return context


@login_required()
def leave_comment(request, bb_id):
    b = Bb.objects.get(id=bb_id)
    b.comment_set.create(author_name=request.user, comm_text=request.POST['text'])
    return redirect(reverse('bboard:detail_bb', kwargs={'bb_id': b.id}))


def rubrics(request):
    RubricFormSet = modelformset_factory(Rubric, fields='__all__', can_delete=True, extra=0)

    if request.method == 'POST':
        formset = RubricFormSet(request.POST)
        if formset.is_valid():
            formset.save()
            return redirect('bboard:index')
        else:
            transaction.rollback()
            return redirect('bboard:add_rubric_formset')

    else:
        formset = RubricFormSet()
    context = {'formset': formset}
    return render(request, 'bboard/rubrics.html', context)


def process_search_results(request):
    if request.method == 'POST':
        sf = SearchRubric(request.POST)
        if sf.is_valid():
            keyword = sf.cleaned_data['keyword']
            rubric_id = sf.cleaned_data['rubric'].pk
            bbs = Bb.objects.filter(rubric=rubric_id, title__iexact=keyword)
            context = {'bbs': bbs}
            return render(request, 'bboard/process_search_results.html', context)
    sf = SearchRubric()
    context = {'form': sf}
    return render(request, 'bboard/search_bb.html', context)


class ImgCreateView(CreateView):
    template_name = 'bboard/add_file.html'
    form_class = ImgForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('bboard:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        return context

bboard/templates/bboard/add_file.html
{% extends "basic.html" %}


{% block title %}Файлы тест{% endblock %}


{% block content %}
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Загрузить изображение и описание">
</form>
{% endblock %}

bboard/templates/bboard/by_rubric.html
{% extends "basic.html" %}

{% block title %}{{ current_rubric.name }}{% endblock %}

{% block content %}
<h2>Рубрика: {{ current_rubric.name }}</h2>
{% if user.is_staff %}
	<em><a href="{% url 'bboard:delete_rubric' current_rubric.pk %}">Удалить рубрику</em>
{% endif %}
<h3><a href="{% url 'bboard:add' %}">Добавить объявление</a></h3>
{% for bb in bbs %}
<div>
	<h2><a href="{% url 'bboard:detail_bb' bb.pk %}">{{ bb.title }}</a></h2>
	<p>{{ bb.content }}</p>
	<p><p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
</div>
{% endfor %}
<input type=button value="Предыдущая страница" onClick="javascript:history.go(-1);">
{% endblock %}

bboard/templates/bboard/create.html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html"; charset="utf-8">
	<title>Добавление объявления - Доска объявлений</title>
</head>
<body>
	<h1>Добавление объявления</h1>
	<div>
		<a href="{% url 'bboard:index' %}">Главная</a>
		{% for rubric in rubrics %}
		<a href="{% url 'bboard:by_rubric' rubric.pk %}">{{ rubric.name }}</a>
		{% endfor %}
	</div>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Добавить">
	</form>	
	<input type=button value="Предыдущая страница" onClick="javascript:history.go(-1);">
</body>
</html>

bboard/templates/bboard/create_a_rubric.html
{% extends "basic.html" %}


{% block title %}Добавление рубрики{% endblock %}


{% block content %}
<h2>Добавление рубрики</h2>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Добавить">
</form>
<input type=button value="Предыдущая страница" onClick="javascript:history.go(-1);">
{% endblock %}

bboard/templates/bboard/delete.html
{% extends "basic.html" %}


{% block title %}Удаление объявления{% endblock %}


{% block content %}
<h2>Удаление объявления: <a href="url 'bboard:detail_bb' bb.pk">{{ bb.title }}</a></h2>
<p>Рубрика: {{ bb.rubric.name }}</p>
<p>Описание: {{ bb.content }}</p>
<p>Цена: {{ bb.price }}</p>
<em>Дата создания: {{ bb.published }}</em>
<form method="post">
	{% csrf_token %}
	<input type="submit" value="Удалить">
</form>
<input type=button value="Предыдущая страница" onClick="javascript:history.go(-1);">	
{% endblock %}

bboard/templates/bboard/delete_rubric.html
{% extends "basic.html" %}


{% block title %}Удаление рубрики{% endblock %}


{% block content %}
<h2>Удаление рубрики: <a href="{% url 'bboard:by_rubric' rubric.pk %}">{{ rubric.name }}</a></h2>
<p>Объявления, которые относятся к данной рубрике:</p>
{% for bb in bbs %}
	<p><a href="{% url 'bboard:detail_bb' bb.pk %}">{{ bb.title }}</p>
{% endfor %}
<form method="post">
	{% csrf_token %}
	<input type="submit" value="Удалить">
</form>
<input type=button value="Предыдущая страница" onClick="javascript:history.go(-1);">
{% endblock %}

bboard/templates/bboard/detail_bb.html
{% extends "basic.html" %}
{% load thumbnail %}

{% block title %}{{ current_bb.title }}{% endblock %}

{% block content %}


<h1>Рубрика: <a href="{% url 'bboard:by_rubric' current_bb.rubric.pk %}">{{ current_bb.rubric.name }}</a></h1>
<h1><a href="{% url 'bboard:add' %}">Добавить объявление</a></h1>
<h1>Объявление: {{ current_bb.title }}</h1>
<h1>Цель объявления: {{ current_bb.kind }}</h1>
{% if current_bb.image %}
<img src="{{ current_bb.image.url }}" alt="{{ current_bb.title }}">
<img src="{{ current_bb.image|thumbnail_url:'default' }}">
{% endif %}
<h1>Описание: <strong>{{ current_bb.content }}</strong></h1>
<h1>Цена: <strong>{{ current_bb.price }}</strong></h1>
<p>Создатель: {{ current_bb.creator }}</p>

<em><strong>{{ current_bb.published|date:"d.m.Y H:i:s" }}</strong></em>

{% if request.user == current_bb.creator %}
<em><a href="{% url 'bboard:edit' current_bb.pk %}">Изменить объявление</a></em>
{% endif %}

<hr>

{% if request.user == current_bb.creator %}
<p><a href="{% url 'bboard:delete' current_bb.pk %}">Удалить объявление</a></p>
{% endif %}

<hr>
<input type=button value="Предыдущая страница" onClick="javascript:history.go(-1);">
<hr>

<form action = "{% url 'bboard:leave_comment' current_bb.id %}" method="POST">

	{% csrf_token %}
	
	<textarea name="text" required="" placeholder="Текст комментария" cols ="30" rows="10"></textarea><br>

	<button type="submite"> Оставить комментарий </button>

</form>

<hr>

{% if latest_comments_list %}

	{% for c in latest_comments_list %}
		<p>
			<strong>{{c.author_name}}</strong>
			<p>{{c.comm_text}}</p>
		</p>
	{% endfor %}

{% else %}
Комментарии не найдены! Станьте первым)
{% endif %}

<hr>

{% endblock %}

bboard/templates/bboard/index.html
{% extends "basic.html" %}

{% block content %}
{% for bb in bbs %}
<div class="b">
	<h2><a href="{% url 'bboard:detail_bb' bb.pk %}">{{ bb.title }}</a></h2>
	<p>{{ bb.content }}</p>
	<p><a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">{{ bb.rubric.name }}</a></p>
	<p><p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
</div>
{% endfor %}
{% endblock %}

bboard/templates/bboard/login.html
{% extends "basic.html" %}


{% block title %}Вход{% endblock %}


{% block content %}
<h2>Вход</h2>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="hidden" name="next" value="{{ next }}">
	<input type="submit" value="Войти">
</form>
{% endblock %}

bboard/templates/bboard/process_search_results.html
{% extends "basic.html" %}


{% block title %}Результаты поиска{% endblock %}


{% block content %}
{% if bbs %}
	{% for bb in bbs %}
	<div>
		<h2><a href="{% url 'bboard:detail_bb' bb.pk %}">{{ bb.title }}</a></h2>
		<p>{{ bb.content }}</p>
		<p><p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
	</div>
	{% endfor %}
{% else %}
<h2>По вашему запросу ничего не найдено :(</h2>
{% endif %}
<input type=button value="Предыдущая страница" onClick="javascript:history.go(-1);">
{% endblock %}

bboard/templates/bboard/register_page.html
{% extends "basic.html" %}


{% block title %}Регистрация{% endblock %}


{% block content %}
<h2>Регистрация</h2>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="hidden" name="next" value="{{ next }}">
	<input type="submit" value="Зарегестрироваться">
</form>
{% endblock %}

bboard/templates/bboard/reset_email.html
{% autoescape off %}
Уважаемый {{ user.username }}!

Вы отправили запрос на сброс пароля. Чтобы выполнить сброс перейдите по этому интернет-адресу:
{{ protocol))://{( domain }}{% url 'password_reset confirm' uidb64=uid token=token %} 

До свидания!
С уважением, администрация сайта "Доска объявлений".
{% endautoescape %}

bboard/templates/bboard/rubrics.html
{% extends "basic.html" %}


{% block content %}
<form method="post">
	{% csrf_token %}
	{{ formset.as_p }}
	<input type="submit" value="Сохранить">
</form>
<input type=button value="Предыдущая страница" onClick="javascript:history.go(-1);">
{% endblock %}

bboard/templates/bboard/search_bb.html
{% extends "basic.html" %}


{% block title %}Найти объявление{% endblock %}


{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Искать">
</form>
<input type=button value="Предыдущая страница" onClick="javascript:history.go(-1);">
{% endblock %}